### ISSUE TITLE
Can't resolve 'react/jsx-runtime' after updating to 0.9.0 version

### ISSUE THREAD

**Issue by stud-mai** [gilbarbara/react-floater#100]
## 🐛 Bug Report

After updating to the latest version of `react-floater` I am getting an error of inability to resolve 'react/jsx-runtime' module while starting a project.
<img width="1157" alt="image" src="https://github.com/gilbarbara/react-floater/assets/17678625/5e07b1df-97a7-47d5-b63d-4e6ca0b363f0">

Same issue with while bundling the project with rollup.
<img width="1172" alt="image" src="https://github.com/gilbarbara/react-floater/assets/17678625/7d70fa97-a142-4f38-aebb-3a91dc6883f2">

Same problem occurs on codesanbox demo (see `link to repl` section)

Issue might be resolved by updating React up to 18 version. In our case it is not acceptable. Moreover it is pointed in package json that React might be 16.8 - 18 version

## Expected behavior

Project starts and bundles without errors

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/fervent-kapitsa-0lp53r?file=/src/components/WithHoverCustomDelay.tsx

## Run `npx envinfo --system --binaries --npmPackages react-floater`

```bash
System:
  OS: macOS 12.6.7
  CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Memory: 61.11 MB / 16.00 GB
  Shell: 3.2.57 - /bin/bash
Binaries:
  Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
  Yarn: 1.22.4 - /usr/local/bin/yarn
  npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
npmPackages:
  react: 16.14.0 => 16.14.0 
  react-floater: 0.9.0 => 0.9.0 
```

**Comment by gilbarbara** [comment]
Hey @stud-mai 

Fixed in v0.9.1

**Comment by stud-mai** [comment]
@gilbarbara thanks!
Unfortunately I still have problems with types in `react-floater/dist/index.d.ts` 😞 
<img width="1307" alt="image" src="https://github.com/gilbarbara/react-floater/assets/17678625/eb6af862-46b1-4a9a-b570-2b9b8cd0c413">

The first problem related to React probably might be resolved by updating `@types/react` package, however the second one no. I guess the root of that problem is `fix-cjs-dts` package, in particular this [code](https://github.com/u3u/fix-tsup-cjs/blob/main/src/fix-cjs-dts.ts). It's easily to reproduce same error in typescript [playground](https://www.typescriptlang.org/play?target=3&jsx=4&module=0&ts=4.7.4#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwCUQpMAxCHKDEGACgAcYd6BnALngG8BfASg5YYYWVAHMA3AChQkWAlRQAtiBb0SCIiQzlK1GF0nwj8AG6x4oRFGQQMABSasOnQ8bfWMOAPL0QqDgBGODgQxKhSbm6gAciigcGhUOGukRZYLFABoeRY9PEhYRGpaRlZIAASOCY0ACo4AMIQWGAA1vmJycXwINWoGAJCIhIpkT1+GAAiINAAnhyoyIoBNEWpABZYoACCMEwA7u2FI244iIgsIP3wC0srx8b00GAgyn0DwmKrkSxrOHuNOAuACFkBhPP54EECkkvtwpNxJJIQAAPeg4GAYLiEYhkChUGjwKAsCwgKw2TFwpGo9GYgC82K0OnxMCAA). However I am not sure who is responsible to resolve this issue
I would appreciate for any help!

**Comment by gilbarbara** [comment]
Hey @stud-mai 

Can you update the codesandbox and replicate the typescript error?
Also, what's in your tsconfig?
Do you have `skipLibCheck` enabled?

**Comment by gilbarbara** [comment]
Hey @stud-mai 
It's "recommended" to turn this flag on since you can't control library code. Check this [video](https://www.youtube.com/watch?v=eJXVEju3XLM) for more information.

Anyway, I've updated the build process to "fix" that. You can try it by installing `react-floater@next`

**Comment by stud-mai** [comment]
Hey @gilbarbara!

Thanks for the "recommendation" but it seems if we choose this way there is no point in lib types at all (flow-type way 😅).

As for updated version `react-floater@next` - it works perfectly fine. Thanks!

**Comment by gilbarbara** [comment]
Cool.

The fix is in v0.9.2

**Comment by HassanHeydariNasab** [comment]
I had this issue in `react-floater@^0.9.5-4` and fixed using [this](https://github.com/vercel/next.js/discussions/34504#discussioncomment-7901652)
